---
server:
  port: 8761
spring:
  profiles: peer1
eureka:
  instance:
    hostname:  peer1
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.instance.instance-id=${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname:  peer2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---
server:
  port: 8763
spring:
  profiles: peer3
eureka:
  instance:
    hostname:  peer3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka