server:
  port: 80
  max-http-header-size: 8192
  tomcat:
    uri-encoding: UTF-8
  
mybatis:
  configuration:
    map-underscore-to-camel-case: false
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration-properties:
    enumAsSimpleTpe: true
    

mapper:
  style: normal

logging:
  level:
    com.fumin.role.demo: warning
  
spring:
  thymeleaf:
    cache: false
    encoding: UTF8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  http:
    encoding:
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/jianhang_pos?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      #关闭自带的icon图标
      enabled: false
