server:
  port: 9999
  
spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      label: master
      server:
        git:
          uri: https://github.com/fuminshen/fmcloud-config
          username: fuminshen
          password: Fm19851031